// Pack data types — single source of truth for all Offisims data shapes.
//
// These types are shared between Studio (authoring) and Game (runtime).
// Studio stores entities as individual JSON files. When compiling a pack,
// Studio serialises them into the binary protobuf Pack message.
// The game server reads packs and runs sessions on top of them.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: offisims/pack/v1/pack.proto

package packv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlacementLayer int32

const (
	PlacementLayer_PLACEMENT_LAYER_UNSPECIFIED PlacementLayer = 0
	PlacementLayer_PLACEMENT_LAYER_FLOOR       PlacementLayer = 1
	PlacementLayer_PLACEMENT_LAYER_OBJECT      PlacementLayer = 2
)

// Enum value maps for PlacementLayer.
var (
	PlacementLayer_name = map[int32]string{
		0: "PLACEMENT_LAYER_UNSPECIFIED",
		1: "PLACEMENT_LAYER_FLOOR",
		2: "PLACEMENT_LAYER_OBJECT",
	}
	PlacementLayer_value = map[string]int32{
		"PLACEMENT_LAYER_UNSPECIFIED": 0,
		"PLACEMENT_LAYER_FLOOR":       1,
		"PLACEMENT_LAYER_OBJECT":      2,
	}
)

func (x PlacementLayer) Enum() *PlacementLayer {
	p := new(PlacementLayer)
	*p = x
	return p
}

func (x PlacementLayer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlacementLayer) Descriptor() protoreflect.EnumDescriptor {
	return file_offisims_pack_v1_pack_proto_enumTypes[0].Descriptor()
}

func (PlacementLayer) Type() protoreflect.EnumType {
	return &file_offisims_pack_v1_pack_proto_enumTypes[0]
}

func (x PlacementLayer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlacementLayer.Descriptor instead.
func (PlacementLayer) EnumDescriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{0}
}

// TilesetDefinition describes a tileset image and its grid layout.
// Each tileset has a unique ID and the metadata needed to interpret
// tile coordinates (tile size, grid dimensions) plus the image path.
type TilesetDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// Image source — URL path (e.g. "/data/tilesets/foo.png") or data-URL.
	Path          string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	TileWidth     int32  `protobuf:"varint,4,opt,name=tile_width,json=tileWidth,proto3" json:"tile_width,omitempty"`
	TileHeight    int32  `protobuf:"varint,5,opt,name=tile_height,json=tileHeight,proto3" json:"tile_height,omitempty"`
	Cols          int32  `protobuf:"varint,6,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32  `protobuf:"varint,7,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TilesetDefinition) Reset() {
	*x = TilesetDefinition{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TilesetDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TilesetDefinition) ProtoMessage() {}

func (x *TilesetDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TilesetDefinition.ProtoReflect.Descriptor instead.
func (*TilesetDefinition) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{0}
}

func (x *TilesetDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TilesetDefinition) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TilesetDefinition) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TilesetDefinition) GetTileWidth() int32 {
	if x != nil {
		return x.TileWidth
	}
	return 0
}

func (x *TilesetDefinition) GetTileHeight() int32 {
	if x != nil {
		return x.TileHeight
	}
	return 0
}

func (x *TilesetDefinition) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TilesetDefinition) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// TilesetRegion is a rectangular region within a tileset image,
// measured in tiles. The fundamental building block for placements
// and composite parts.
type TilesetRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TilesetId     string                 `protobuf:"bytes,1,opt,name=tileset_id,json=tilesetId,proto3" json:"tileset_id,omitempty"`
	SrcCol        int32                  `protobuf:"varint,2,opt,name=src_col,json=srcCol,proto3" json:"src_col,omitempty"`
	SrcRow        int32                  `protobuf:"varint,3,opt,name=src_row,json=srcRow,proto3" json:"src_row,omitempty"`
	W             int32                  `protobuf:"varint,4,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,5,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TilesetRegion) Reset() {
	*x = TilesetRegion{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TilesetRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TilesetRegion) ProtoMessage() {}

func (x *TilesetRegion) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TilesetRegion.ProtoReflect.Descriptor instead.
func (*TilesetRegion) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{1}
}

func (x *TilesetRegion) GetTilesetId() string {
	if x != nil {
		return x.TilesetId
	}
	return ""
}

func (x *TilesetRegion) GetSrcCol() int32 {
	if x != nil {
		return x.SrcCol
	}
	return 0
}

func (x *TilesetRegion) GetSrcRow() int32 {
	if x != nil {
		return x.SrcRow
	}
	return 0
}

func (x *TilesetRegion) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *TilesetRegion) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

// CompositePart is one piece of a composite object — a tileset region
// positioned within the composite's local coordinate space.
type CompositePart struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Region  *TilesetRegion         `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	OffsetX int32                  `protobuf:"varint,2,opt,name=offset_x,json=offsetX,proto3" json:"offset_x,omitempty"`
	OffsetY int32                  `protobuf:"varint,3,opt,name=offset_y,json=offsetY,proto3" json:"offset_y,omitempty"`
	// Manual z-order bias for render-time sorting within the composite.
	// Added to the anchor Y (bottom edge) when computing sort order.
	ZBias         int32 `protobuf:"varint,4,opt,name=z_bias,json=zBias,proto3" json:"z_bias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositePart) Reset() {
	*x = CompositePart{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositePart) ProtoMessage() {}

func (x *CompositePart) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositePart.ProtoReflect.Descriptor instead.
func (*CompositePart) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{2}
}

func (x *CompositePart) GetRegion() *TilesetRegion {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *CompositePart) GetOffsetX() int32 {
	if x != nil {
		return x.OffsetX
	}
	return 0
}

func (x *CompositePart) GetOffsetY() int32 {
	if x != nil {
		return x.OffsetY
	}
	return 0
}

func (x *CompositePart) GetZBias() int32 {
	if x != nil {
		return x.ZBias
	}
	return 0
}

// CompositeObject is a multi-tile object assembled from tileset regions.
// Used for large objects that span multiple regions (e.g. a conference table).
type CompositeObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Parts []*CompositePart       `protobuf:"bytes,4,rep,name=parts,proto3" json:"parts,omitempty"`
	// Total display size in tiles (computed from parts bounding box).
	DisplayWidth  int32 `protobuf:"varint,5,opt,name=display_width,json=displayWidth,proto3" json:"display_width,omitempty"`
	DisplayHeight int32 `protobuf:"varint,6,opt,name=display_height,json=displayHeight,proto3" json:"display_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeObject) Reset() {
	*x = CompositeObject{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeObject) ProtoMessage() {}

func (x *CompositeObject) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeObject.ProtoReflect.Descriptor instead.
func (*CompositeObject) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{3}
}

func (x *CompositeObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompositeObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompositeObject) GetParts() []*CompositePart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *CompositeObject) GetDisplayWidth() int32 {
	if x != nil {
		return x.DisplayWidth
	}
	return 0
}

func (x *CompositeObject) GetDisplayHeight() int32 {
	if x != nil {
		return x.DisplayHeight
	}
	return 0
}

// DoorDefinition is a single-tile teleport point connecting two rooms.
// Target format: "roomName#doorId" (e.g. "lobby#door-2").
// An empty target means the door is not yet connected.
type DoorDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Col           int32                  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Row           int32                  `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoorDefinition) Reset() {
	*x = DoorDefinition{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoorDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoorDefinition) ProtoMessage() {}

func (x *DoorDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoorDefinition.ProtoReflect.Descriptor instead.
func (*DoorDefinition) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{4}
}

func (x *DoorDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DoorDefinition) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *DoorDefinition) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *DoorDefinition) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// TexturePlacement is a visual element placed on the room grid.
// References either a tileset region directly, or a composite by ID.
// Multiple textures can stack on the same tile.
type TexturePlacement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	GridX int32                  `protobuf:"varint,1,opt,name=grid_x,json=gridX,proto3" json:"grid_x,omitempty"`
	GridY int32                  `protobuf:"varint,2,opt,name=grid_y,json=gridY,proto3" json:"grid_y,omitempty"`
	Layer PlacementLayer         `protobuf:"varint,3,opt,name=layer,proto3,enum=offisims.pack.v1.PlacementLayer" json:"layer,omitempty"`
	// For direct tileset placements. Unset if composite_id is used.
	Region *TilesetRegion `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	// For composite placements. Empty if region is used.
	CompositeId string `protobuf:"bytes,5,opt,name=composite_id,json=compositeId,proto3" json:"composite_id,omitempty"`
	// Manual z-order bias for render-time sorting.
	ZBias         int32 `protobuf:"varint,6,opt,name=z_bias,json=zBias,proto3" json:"z_bias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TexturePlacement) Reset() {
	*x = TexturePlacement{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexturePlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexturePlacement) ProtoMessage() {}

func (x *TexturePlacement) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexturePlacement.ProtoReflect.Descriptor instead.
func (*TexturePlacement) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{5}
}

func (x *TexturePlacement) GetGridX() int32 {
	if x != nil {
		return x.GridX
	}
	return 0
}

func (x *TexturePlacement) GetGridY() int32 {
	if x != nil {
		return x.GridY
	}
	return 0
}

func (x *TexturePlacement) GetLayer() PlacementLayer {
	if x != nil {
		return x.Layer
	}
	return PlacementLayer_PLACEMENT_LAYER_UNSPECIFIED
}

func (x *TexturePlacement) GetRegion() *TilesetRegion {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *TexturePlacement) GetCompositeId() string {
	if x != nil {
		return x.CompositeId
	}
	return ""
}

func (x *TexturePlacement) GetZBias() int32 {
	if x != nil {
		return x.ZBias
	}
	return 0
}

// RoomDefinition holds layout (walkability, doors) and texture placements.
type RoomDefinition struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Width  int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// Flat array of width*height booleans. Index = row * width + col.
	// true = walkable, false = blocked.
	Walkability   []bool              `protobuf:"varint,4,rep,packed,name=walkability,proto3" json:"walkability,omitempty"`
	Doors         []*DoorDefinition   `protobuf:"bytes,5,rep,name=doors,proto3" json:"doors,omitempty"`
	Placements    []*TexturePlacement `protobuf:"bytes,6,rep,name=placements,proto3" json:"placements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomDefinition) Reset() {
	*x = RoomDefinition{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDefinition) ProtoMessage() {}

func (x *RoomDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDefinition.ProtoReflect.Descriptor instead.
func (*RoomDefinition) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{6}
}

func (x *RoomDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomDefinition) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RoomDefinition) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RoomDefinition) GetWalkability() []bool {
	if x != nil {
		return x.Walkability
	}
	return nil
}

func (x *RoomDefinition) GetDoors() []*DoorDefinition {
	if x != nil {
		return x.Doors
	}
	return nil
}

func (x *RoomDefinition) GetPlacements() []*TexturePlacement {
	if x != nil {
		return x.Placements
	}
	return nil
}

// ResourceFrame is a single frame referencing a rectangular tile region
// in a source tileset image. Coordinates are in tiles (not pixels).
type ResourceFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TilesetId     string                 `protobuf:"bytes,1,opt,name=tileset_id,json=tilesetId,proto3" json:"tileset_id,omitempty"`
	SrcCol        int32                  `protobuf:"varint,2,opt,name=src_col,json=srcCol,proto3" json:"src_col,omitempty"`
	SrcRow        int32                  `protobuf:"varint,3,opt,name=src_row,json=srcRow,proto3" json:"src_row,omitempty"`
	W             int32                  `protobuf:"varint,4,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,5,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceFrame) Reset() {
	*x = ResourceFrame{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceFrame) ProtoMessage() {}

func (x *ResourceFrame) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceFrame.ProtoReflect.Descriptor instead.
func (*ResourceFrame) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceFrame) GetTilesetId() string {
	if x != nil {
		return x.TilesetId
	}
	return ""
}

func (x *ResourceFrame) GetSrcCol() int32 {
	if x != nil {
		return x.SrcCol
	}
	return 0
}

func (x *ResourceFrame) GetSrcRow() int32 {
	if x != nil {
		return x.SrcRow
	}
	return 0
}

func (x *ResourceFrame) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *ResourceFrame) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

// Resource is a tagged sequence of frames. A static sprite has one frame.
// Resources are tagged with arbitrary strings for grouping, filtering,
// and semantic meaning. A "character" is a set of resources sharing a
// common group tag (e.g. "adam") with animation tags ("idle", "walk", etc.).
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Frames        []*ResourceFrame       `protobuf:"bytes,4,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{8}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Resource) GetFrames() []*ResourceFrame {
	if x != nil {
		return x.Frames
	}
	return nil
}

// MaskCut defines one cut within a mask template.
// When applied, each cut creates one Resource.
type MaskCut struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Tags       []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Row        int32                  `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	StartFrame int32                  `protobuf:"varint,3,opt,name=start_frame,json=startFrame,proto3" json:"start_frame,omitempty"`
	FrameCount int32                  `protobuf:"varint,4,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	// Width/height of each frame in tiles. 0 means 1 (default).
	FrameWidth    int32 `protobuf:"varint,5,opt,name=frame_width,json=frameWidth,proto3" json:"frame_width,omitempty"`
	FrameHeight   int32 `protobuf:"varint,6,opt,name=frame_height,json=frameHeight,proto3" json:"frame_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaskCut) Reset() {
	*x = MaskCut{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaskCut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskCut) ProtoMessage() {}

func (x *MaskCut) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskCut.ProtoReflect.Descriptor instead.
func (*MaskCut) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{9}
}

func (x *MaskCut) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MaskCut) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *MaskCut) GetStartFrame() int32 {
	if x != nil {
		return x.StartFrame
	}
	return 0
}

func (x *MaskCut) GetFrameCount() int32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *MaskCut) GetFrameWidth() int32 {
	if x != nil {
		return x.FrameWidth
	}
	return 0
}

func (x *MaskCut) GetFrameHeight() int32 {
	if x != nil {
		return x.FrameHeight
	}
	return 0
}

// Mask is a reusable cut template for batch-creating tagged resources
// from a tileset. Created by the Tile Cutter: you manually cut a tileset
// into resources, then "Save as Mask" captures the cut pattern. Later,
// the same mask can be applied to a different tileset of the same shape.
type Mask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TileWidth     int32                  `protobuf:"varint,3,opt,name=tile_width,json=tileWidth,proto3" json:"tile_width,omitempty"`
	TileHeight    int32                  `protobuf:"varint,4,opt,name=tile_height,json=tileHeight,proto3" json:"tile_height,omitempty"`
	Cuts          []*MaskCut             `protobuf:"bytes,5,rep,name=cuts,proto3" json:"cuts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mask) Reset() {
	*x = Mask{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mask) ProtoMessage() {}

func (x *Mask) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mask.ProtoReflect.Descriptor instead.
func (*Mask) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{10}
}

func (x *Mask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mask) GetTileWidth() int32 {
	if x != nil {
		return x.TileWidth
	}
	return 0
}

func (x *Mask) GetTileHeight() int32 {
	if x != nil {
		return x.TileHeight
	}
	return 0
}

func (x *Mask) GetCuts() []*MaskCut {
	if x != nil {
		return x.Cuts
	}
	return nil
}

// PackManifest is the identity and metadata of a pack.
// Stored as manifest.json (human-readable) alongside the binary data.
type PackManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Created       string                 `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"` // ISO-8601
	Updated       string                 `protobuf:"bytes,7,opt,name=updated,proto3" json:"updated,omitempty"` // ISO-8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackManifest) Reset() {
	*x = PackManifest{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackManifest) ProtoMessage() {}

func (x *PackManifest) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackManifest.ProtoReflect.Descriptor instead.
func (*PackManifest) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{11}
}

func (x *PackManifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PackManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PackManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackManifest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PackManifest) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *PackManifest) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

// Pack is the top-level container — a bundle of rooms, resources,
// tilesets, composites and masks. Studio authors packs; the game
// server loads them and runs sessions on top of them.
type Pack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *PackManifest          `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Tilesets      []*TilesetDefinition   `protobuf:"bytes,2,rep,name=tilesets,proto3" json:"tilesets,omitempty"`
	Composites    []*CompositeObject     `protobuf:"bytes,3,rep,name=composites,proto3" json:"composites,omitempty"`
	Rooms         []*RoomDefinition      `protobuf:"bytes,4,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Resources     []*Resource            `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	Masks         []*Mask                `protobuf:"bytes,6,rep,name=masks,proto3" json:"masks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pack) Reset() {
	*x = Pack{}
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pack) ProtoMessage() {}

func (x *Pack) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_pack_v1_pack_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pack.ProtoReflect.Descriptor instead.
func (*Pack) Descriptor() ([]byte, []int) {
	return file_offisims_pack_v1_pack_proto_rawDescGZIP(), []int{12}
}

func (x *Pack) GetManifest() *PackManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *Pack) GetTilesets() []*TilesetDefinition {
	if x != nil {
		return x.Tilesets
	}
	return nil
}

func (x *Pack) GetComposites() []*CompositeObject {
	if x != nil {
		return x.Composites
	}
	return nil
}

func (x *Pack) GetRooms() []*RoomDefinition {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *Pack) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Pack) GetMasks() []*Mask {
	if x != nil {
		return x.Masks
	}
	return nil
}

var File_offisims_pack_v1_pack_proto protoreflect.FileDescriptor

const file_offisims_pack_v1_pack_proto_rawDesc = "" +
	"\n" +
	"\x1boffisims/pack/v1/pack.proto\x12\x10offisims.pack.v1\"\xb5\x01\n" +
	"\x11TilesetDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"tile_width\x18\x04 \x01(\x05R\ttileWidth\x12\x1f\n" +
	"\vtile_height\x18\x05 \x01(\x05R\n" +
	"tileHeight\x12\x12\n" +
	"\x04cols\x18\x06 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\a \x01(\x05R\x04rows\"|\n" +
	"\rTilesetRegion\x12\x1d\n" +
	"\n" +
	"tileset_id\x18\x01 \x01(\tR\ttilesetId\x12\x17\n" +
	"\asrc_col\x18\x02 \x01(\x05R\x06srcCol\x12\x17\n" +
	"\asrc_row\x18\x03 \x01(\x05R\x06srcRow\x12\f\n" +
	"\x01w\x18\x04 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x05 \x01(\x05R\x01h\"\x95\x01\n" +
	"\rCompositePart\x127\n" +
	"\x06region\x18\x01 \x01(\v2\x1f.offisims.pack.v1.TilesetRegionR\x06region\x12\x19\n" +
	"\boffset_x\x18\x02 \x01(\x05R\aoffsetX\x12\x19\n" +
	"\boffset_y\x18\x03 \x01(\x05R\aoffsetY\x12\x15\n" +
	"\x06z_bias\x18\x04 \x01(\x05R\x05zBias\"\xbe\x01\n" +
	"\x0fCompositeObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\x05parts\x18\x04 \x03(\v2\x1f.offisims.pack.v1.CompositePartR\x05parts\x12#\n" +
	"\rdisplay_width\x18\x05 \x01(\x05R\fdisplayWidth\x12%\n" +
	"\x0edisplay_height\x18\x06 \x01(\x05R\rdisplayHeightJ\x04\b\x03\x10\x04\"\\\n" +
	"\x0eDoorDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03col\x18\x02 \x01(\x05R\x03col\x12\x10\n" +
	"\x03row\x18\x03 \x01(\x05R\x03row\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\"\xeb\x01\n" +
	"\x10TexturePlacement\x12\x15\n" +
	"\x06grid_x\x18\x01 \x01(\x05R\x05gridX\x12\x15\n" +
	"\x06grid_y\x18\x02 \x01(\x05R\x05gridY\x126\n" +
	"\x05layer\x18\x03 \x01(\x0e2 .offisims.pack.v1.PlacementLayerR\x05layer\x127\n" +
	"\x06region\x18\x04 \x01(\v2\x1f.offisims.pack.v1.TilesetRegionR\x06region\x12!\n" +
	"\fcomposite_id\x18\x05 \x01(\tR\vcompositeId\x12\x15\n" +
	"\x06z_bias\x18\x06 \x01(\x05R\x05zBias\"\xf0\x01\n" +
	"\x0eRoomDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12 \n" +
	"\vwalkability\x18\x04 \x03(\bR\vwalkability\x126\n" +
	"\x05doors\x18\x05 \x03(\v2 .offisims.pack.v1.DoorDefinitionR\x05doors\x12B\n" +
	"\n" +
	"placements\x18\x06 \x03(\v2\".offisims.pack.v1.TexturePlacementR\n" +
	"placements\"|\n" +
	"\rResourceFrame\x12\x1d\n" +
	"\n" +
	"tileset_id\x18\x01 \x01(\tR\ttilesetId\x12\x17\n" +
	"\asrc_col\x18\x02 \x01(\x05R\x06srcCol\x12\x17\n" +
	"\asrc_row\x18\x03 \x01(\x05R\x06srcRow\x12\f\n" +
	"\x01w\x18\x04 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x05 \x01(\x05R\x01h\"{\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x127\n" +
	"\x06frames\x18\x04 \x03(\v2\x1f.offisims.pack.v1.ResourceFrameR\x06frames\"\xb5\x01\n" +
	"\aMaskCut\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\x12\x10\n" +
	"\x03row\x18\x02 \x01(\x05R\x03row\x12\x1f\n" +
	"\vstart_frame\x18\x03 \x01(\x05R\n" +
	"startFrame\x12\x1f\n" +
	"\vframe_count\x18\x04 \x01(\x05R\n" +
	"frameCount\x12\x1f\n" +
	"\vframe_width\x18\x05 \x01(\x05R\n" +
	"frameWidth\x12!\n" +
	"\fframe_height\x18\x06 \x01(\x05R\vframeHeight\"\x99\x01\n" +
	"\x04Mask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"tile_width\x18\x03 \x01(\x05R\ttileWidth\x12\x1f\n" +
	"\vtile_height\x18\x04 \x01(\x05R\n" +
	"tileHeight\x12-\n" +
	"\x04cuts\x18\x05 \x03(\v2\x19.offisims.pack.v1.MaskCutR\x04cuts\"\xba\x01\n" +
	"\fPackManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x18\n" +
	"\acreated\x18\x06 \x01(\tR\acreated\x12\x18\n" +
	"\aupdated\x18\a \x01(\tR\aupdated\"\xe6\x02\n" +
	"\x04Pack\x12:\n" +
	"\bmanifest\x18\x01 \x01(\v2\x1e.offisims.pack.v1.PackManifestR\bmanifest\x12?\n" +
	"\btilesets\x18\x02 \x03(\v2#.offisims.pack.v1.TilesetDefinitionR\btilesets\x12A\n" +
	"\n" +
	"composites\x18\x03 \x03(\v2!.offisims.pack.v1.CompositeObjectR\n" +
	"composites\x126\n" +
	"\x05rooms\x18\x04 \x03(\v2 .offisims.pack.v1.RoomDefinitionR\x05rooms\x128\n" +
	"\tresources\x18\x05 \x03(\v2\x1a.offisims.pack.v1.ResourceR\tresources\x12,\n" +
	"\x05masks\x18\x06 \x03(\v2\x16.offisims.pack.v1.MaskR\x05masks*h\n" +
	"\x0ePlacementLayer\x12\x1f\n" +
	"\x1bPLACEMENT_LAYER_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PLACEMENT_LAYER_FLOOR\x10\x01\x12\x1a\n" +
	"\x16PLACEMENT_LAYER_OBJECT\x10\x02B\xae\x01\n" +
	"\x14com.offisims.pack.v1B\tPackProtoP\x01Z)github.com/offisims/shared/pack/pb/packv1\xa2\x02\x03OPX\xaa\x02\x10Offisims.Pack.V1\xca\x02\x10Offisims\\Pack\\V1\xe2\x02\x1cOffisims\\Pack\\V1\\GPBMetadata\xea\x02\x12Offisims::Pack::V1b\x06proto3"

var (
	file_offisims_pack_v1_pack_proto_rawDescOnce sync.Once
	file_offisims_pack_v1_pack_proto_rawDescData []byte
)

func file_offisims_pack_v1_pack_proto_rawDescGZIP() []byte {
	file_offisims_pack_v1_pack_proto_rawDescOnce.Do(func() {
		file_offisims_pack_v1_pack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_offisims_pack_v1_pack_proto_rawDesc), len(file_offisims_pack_v1_pack_proto_rawDesc)))
	})
	return file_offisims_pack_v1_pack_proto_rawDescData
}

var file_offisims_pack_v1_pack_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_offisims_pack_v1_pack_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_offisims_pack_v1_pack_proto_goTypes = []any{
	(PlacementLayer)(0),       // 0: offisims.pack.v1.PlacementLayer
	(*TilesetDefinition)(nil), // 1: offisims.pack.v1.TilesetDefinition
	(*TilesetRegion)(nil),     // 2: offisims.pack.v1.TilesetRegion
	(*CompositePart)(nil),     // 3: offisims.pack.v1.CompositePart
	(*CompositeObject)(nil),   // 4: offisims.pack.v1.CompositeObject
	(*DoorDefinition)(nil),    // 5: offisims.pack.v1.DoorDefinition
	(*TexturePlacement)(nil),  // 6: offisims.pack.v1.TexturePlacement
	(*RoomDefinition)(nil),    // 7: offisims.pack.v1.RoomDefinition
	(*ResourceFrame)(nil),     // 8: offisims.pack.v1.ResourceFrame
	(*Resource)(nil),          // 9: offisims.pack.v1.Resource
	(*MaskCut)(nil),           // 10: offisims.pack.v1.MaskCut
	(*Mask)(nil),              // 11: offisims.pack.v1.Mask
	(*PackManifest)(nil),      // 12: offisims.pack.v1.PackManifest
	(*Pack)(nil),              // 13: offisims.pack.v1.Pack
}
var file_offisims_pack_v1_pack_proto_depIdxs = []int32{
	2,  // 0: offisims.pack.v1.CompositePart.region:type_name -> offisims.pack.v1.TilesetRegion
	3,  // 1: offisims.pack.v1.CompositeObject.parts:type_name -> offisims.pack.v1.CompositePart
	0,  // 2: offisims.pack.v1.TexturePlacement.layer:type_name -> offisims.pack.v1.PlacementLayer
	2,  // 3: offisims.pack.v1.TexturePlacement.region:type_name -> offisims.pack.v1.TilesetRegion
	5,  // 4: offisims.pack.v1.RoomDefinition.doors:type_name -> offisims.pack.v1.DoorDefinition
	6,  // 5: offisims.pack.v1.RoomDefinition.placements:type_name -> offisims.pack.v1.TexturePlacement
	8,  // 6: offisims.pack.v1.Resource.frames:type_name -> offisims.pack.v1.ResourceFrame
	10, // 7: offisims.pack.v1.Mask.cuts:type_name -> offisims.pack.v1.MaskCut
	12, // 8: offisims.pack.v1.Pack.manifest:type_name -> offisims.pack.v1.PackManifest
	1,  // 9: offisims.pack.v1.Pack.tilesets:type_name -> offisims.pack.v1.TilesetDefinition
	4,  // 10: offisims.pack.v1.Pack.composites:type_name -> offisims.pack.v1.CompositeObject
	7,  // 11: offisims.pack.v1.Pack.rooms:type_name -> offisims.pack.v1.RoomDefinition
	9,  // 12: offisims.pack.v1.Pack.resources:type_name -> offisims.pack.v1.Resource
	11, // 13: offisims.pack.v1.Pack.masks:type_name -> offisims.pack.v1.Mask
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_offisims_pack_v1_pack_proto_init() }
func file_offisims_pack_v1_pack_proto_init() {
	if File_offisims_pack_v1_pack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_offisims_pack_v1_pack_proto_rawDesc), len(file_offisims_pack_v1_pack_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_offisims_pack_v1_pack_proto_goTypes,
		DependencyIndexes: file_offisims_pack_v1_pack_proto_depIdxs,
		EnumInfos:         file_offisims_pack_v1_pack_proto_enumTypes,
		MessageInfos:      file_offisims_pack_v1_pack_proto_msgTypes,
	}.Build()
	File_offisims_pack_v1_pack_proto = out.File
	file_offisims_pack_v1_pack_proto_goTypes = nil
	file_offisims_pack_v1_pack_proto_depIdxs = nil
}
