// Game WebSocket protocol — binary protobuf over MessageBinary frames.
//
// The server is authoritative. Clients send intents, the server validates
// and broadcasts state updates.
//
// Movement model: client-side prediction with server reconciliation.
// The client moves locally (pixel-granular, local collision check),
// sends position updates ~15/sec while moving, and the server validates
// and relays to other clients in the same room.
//
// A single GameMessage envelope wraps all message types via oneof.
// This replaces the JSON { type: "..." } discriminator pattern.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: offisims/protocol/v1/protocol.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_DOWN        Direction = 1
	Direction_DIRECTION_UP          Direction = 2
	Direction_DIRECTION_LEFT        Direction = 3
	Direction_DIRECTION_RIGHT       Direction = 4
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_DOWN",
		2: "DIRECTION_UP",
		3: "DIRECTION_LEFT",
		4: "DIRECTION_RIGHT",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_DOWN":        1,
		"DIRECTION_UP":          2,
		"DIRECTION_LEFT":        3,
		"DIRECTION_RIGHT":       4,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_offisims_protocol_v1_protocol_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_offisims_protocol_v1_protocol_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{0}
}

// Full avatar state snapshot sent to clients.
type AvatarSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Character resource group ID (references a tag group in the pack).
	CharacterId string    `protobuf:"bytes,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Room        string    `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	X           float32   `protobuf:"fixed32,5,opt,name=x,proto3" json:"x,omitempty"`
	Y           float32   `protobuf:"fixed32,6,opt,name=y,proto3" json:"y,omitempty"`
	Direction   Direction `protobuf:"varint,7,opt,name=direction,proto3,enum=offisims.protocol.v1.Direction" json:"direction,omitempty"`
	Moving      bool      `protobuf:"varint,8,opt,name=moving,proto3" json:"moving,omitempty"`
	// Current animation family (e.g. "idle", "walk").
	Family        string `protobuf:"bytes,9,opt,name=family,proto3" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarSnapshot) Reset() {
	*x = AvatarSnapshot{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarSnapshot) ProtoMessage() {}

func (x *AvatarSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarSnapshot.ProtoReflect.Descriptor instead.
func (*AvatarSnapshot) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *AvatarSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AvatarSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AvatarSnapshot) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *AvatarSnapshot) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *AvatarSnapshot) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AvatarSnapshot) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *AvatarSnapshot) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *AvatarSnapshot) GetMoving() bool {
	if x != nil {
		return x.Moving
	}
	return false
}

func (x *AvatarSnapshot) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

// Room snapshot sent to clients on join / room change.
type RoomSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomSnapshot) Reset() {
	*x = RoomSnapshot{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSnapshot) ProtoMessage() {}

func (x *RoomSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSnapshot.ProtoReflect.Descriptor instead.
func (*RoomSnapshot) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *RoomSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomSnapshot) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RoomSnapshot) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Client requests to join the game.
// The token is obtained via POST /api/register and identifies the player.
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Client reports its avatar's position.
// Sent periodically while moving (~15/sec).
type PositionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Direction     Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=offisims.protocol.v1.Direction" json:"direction,omitempty"`
	Moving        bool                   `protobuf:"varint,4,opt,name=moving,proto3" json:"moving,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionUpdate) Reset() {
	*x = PositionUpdate{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionUpdate) ProtoMessage() {}

func (x *PositionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionUpdate.ProtoReflect.Descriptor instead.
func (*PositionUpdate) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *PositionUpdate) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PositionUpdate) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PositionUpdate) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *PositionUpdate) GetMoving() bool {
	if x != nil {
		return x.Moving
	}
	return false
}

// Client requests to use a door (teleport to another room).
type UseDoor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoorId        string                 `protobuf:"bytes,1,opt,name=door_id,json=doorId,proto3" json:"door_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseDoor) Reset() {
	*x = UseDoor{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseDoor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseDoor) ProtoMessage() {}

func (x *UseDoor) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseDoor.ProtoReflect.Descriptor instead.
func (*UseDoor) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *UseDoor) GetDoorId() string {
	if x != nil {
		return x.DoorId
	}
	return ""
}

// Client sends a chat message to the current room.
type ChatSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSend) Reset() {
	*x = ChatSend{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSend) ProtoMessage() {}

func (x *ChatSend) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSend.ProtoReflect.Descriptor instead.
func (*ChatSend) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *ChatSend) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Client sends a private message to a specific avatar.
type PrivateMessageSend struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetAvatarId string                 `protobuf:"bytes,1,opt,name=target_avatar_id,json=targetAvatarId,proto3" json:"target_avatar_id,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrivateMessageSend) Reset() {
	*x = PrivateMessageSend{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateMessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateMessageSend) ProtoMessage() {}

func (x *PrivateMessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateMessageSend.ProtoReflect.Descriptor instead.
func (*PrivateMessageSend) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *PrivateMessageSend) GetTargetAvatarId() string {
	if x != nil {
		return x.TargetAvatarId
	}
	return ""
}

func (x *PrivateMessageSend) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Client requests to leave the game (graceful disconnect).
type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{7}
}

// Sent to a client immediately after joining.
type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarId      string                 `protobuf:"bytes,1,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	Room          *RoomSnapshot          `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	SpawnX        float32                `protobuf:"fixed32,3,opt,name=spawn_x,json=spawnX,proto3" json:"spawn_x,omitempty"`
	SpawnY        float32                `protobuf:"fixed32,4,opt,name=spawn_y,json=spawnY,proto3" json:"spawn_y,omitempty"`
	Avatars       []*AvatarSnapshot      `protobuf:"bytes,5,rep,name=avatars,proto3" json:"avatars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *Welcome) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

func (x *Welcome) GetRoom() *RoomSnapshot {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *Welcome) GetSpawnX() float32 {
	if x != nil {
		return x.SpawnX
	}
	return 0
}

func (x *Welcome) GetSpawnY() float32 {
	if x != nil {
		return x.SpawnY
	}
	return 0
}

func (x *Welcome) GetAvatars() []*AvatarSnapshot {
	if x != nil {
		return x.Avatars
	}
	return nil
}

// Broadcast when a new avatar enters the client's current room.
type AvatarJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avatar        *AvatarSnapshot        `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarJoin) Reset() {
	*x = AvatarJoin{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarJoin) ProtoMessage() {}

func (x *AvatarJoin) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarJoin.ProtoReflect.Descriptor instead.
func (*AvatarJoin) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *AvatarJoin) GetAvatar() *AvatarSnapshot {
	if x != nil {
		return x.Avatar
	}
	return nil
}

// Broadcast when an avatar leaves the client's current room.
type AvatarLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarId      string                 `protobuf:"bytes,1,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarLeave) Reset() {
	*x = AvatarLeave{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarLeave) ProtoMessage() {}

func (x *AvatarLeave) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarLeave.ProtoReflect.Descriptor instead.
func (*AvatarLeave) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *AvatarLeave) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

// Broadcast when another avatar moves within the client's current room.
// Clients interpolate between position updates for smooth rendering.
type AvatarMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarId      string                 `protobuf:"bytes,1,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Direction     Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=offisims.protocol.v1.Direction" json:"direction,omitempty"`
	Moving        bool                   `protobuf:"varint,5,opt,name=moving,proto3" json:"moving,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarMove) Reset() {
	*x = AvatarMove{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarMove) ProtoMessage() {}

func (x *AvatarMove) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarMove.ProtoReflect.Descriptor instead.
func (*AvatarMove) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *AvatarMove) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

func (x *AvatarMove) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AvatarMove) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *AvatarMove) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *AvatarMove) GetMoving() bool {
	if x != nil {
		return x.Moving
	}
	return false
}

// Sent to a client when their avatar transitions to a new room.
type RoomChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *RoomSnapshot          `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	SpawnX        float32                `protobuf:"fixed32,2,opt,name=spawn_x,json=spawnX,proto3" json:"spawn_x,omitempty"`
	SpawnY        float32                `protobuf:"fixed32,3,opt,name=spawn_y,json=spawnY,proto3" json:"spawn_y,omitempty"`
	Avatars       []*AvatarSnapshot      `protobuf:"bytes,4,rep,name=avatars,proto3" json:"avatars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomChange) Reset() {
	*x = RoomChange{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomChange) ProtoMessage() {}

func (x *RoomChange) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomChange.ProtoReflect.Descriptor instead.
func (*RoomChange) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *RoomChange) GetRoom() *RoomSnapshot {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *RoomChange) GetSpawnX() float32 {
	if x != nil {
		return x.SpawnX
	}
	return 0
}

func (x *RoomChange) GetSpawnY() float32 {
	if x != nil {
		return x.SpawnY
	}
	return 0
}

func (x *RoomChange) GetAvatars() []*AvatarSnapshot {
	if x != nil {
		return x.Avatars
	}
	return nil
}

// Chat message from an avatar in the client's current room.
type ChatReceive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarId      string                 `protobuf:"bytes,1,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReceive) Reset() {
	*x = ChatReceive{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReceive) ProtoMessage() {}

func (x *ChatReceive) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReceive.ProtoReflect.Descriptor instead.
func (*ChatReceive) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *ChatReceive) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

func (x *ChatReceive) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatReceive) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Private message between two avatars.
type PrivateMessageReceive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAvatarId  string                 `protobuf:"bytes,1,opt,name=from_avatar_id,json=fromAvatarId,proto3" json:"from_avatar_id,omitempty"`
	FromName      string                 `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	ToAvatarId    string                 `protobuf:"bytes,3,opt,name=to_avatar_id,json=toAvatarId,proto3" json:"to_avatar_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateMessageReceive) Reset() {
	*x = PrivateMessageReceive{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateMessageReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateMessageReceive) ProtoMessage() {}

func (x *PrivateMessageReceive) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateMessageReceive.ProtoReflect.Descriptor instead.
func (*PrivateMessageReceive) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *PrivateMessageReceive) GetFromAvatarId() string {
	if x != nil {
		return x.FromAvatarId
	}
	return ""
}

func (x *PrivateMessageReceive) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *PrivateMessageReceive) GetToAvatarId() string {
	if x != nil {
		return x.ToAvatarId
	}
	return ""
}

func (x *PrivateMessageReceive) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Server corrects the client's avatar position.
// Sent when the server detects an invalid client position (e.g. inside a wall).
type Snap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snap) Reset() {
	*x = Snap{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snap) ProtoMessage() {}

func (x *Snap) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snap.ProtoReflect.Descriptor instead.
func (*Snap) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *Snap) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Snap) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Server reports an error to the client.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Single wrapper message — both client and server use this envelope.
// The oneof payload determines the message type.
type GameMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GameMessage_Join
	//	*GameMessage_Position
	//	*GameMessage_UseDoor
	//	*GameMessage_Chat
	//	*GameMessage_PrivateMessage
	//	*GameMessage_Leave
	//	*GameMessage_Welcome
	//	*GameMessage_AvatarJoin
	//	*GameMessage_AvatarLeave
	//	*GameMessage_AvatarMove
	//	*GameMessage_RoomChange
	//	*GameMessage_ChatMessage
	//	*GameMessage_PrivateMessageReceive
	//	*GameMessage_Snap
	//	*GameMessage_Error
	Payload       isGameMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_offisims_protocol_v1_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_offisims_protocol_v1_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *GameMessage) GetPayload() isGameMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameMessage) GetJoin() *JoinRequest {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *GameMessage) GetPosition() *PositionUpdate {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Position); ok {
			return x.Position
		}
	}
	return nil
}

func (x *GameMessage) GetUseDoor() *UseDoor {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_UseDoor); ok {
			return x.UseDoor
		}
	}
	return nil
}

func (x *GameMessage) GetChat() *ChatSend {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *GameMessage) GetPrivateMessage() *PrivateMessageSend {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_PrivateMessage); ok {
			return x.PrivateMessage
		}
	}
	return nil
}

func (x *GameMessage) GetLeave() *LeaveRequest {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Leave); ok {
			return x.Leave
		}
	}
	return nil
}

func (x *GameMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *GameMessage) GetAvatarJoin() *AvatarJoin {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_AvatarJoin); ok {
			return x.AvatarJoin
		}
	}
	return nil
}

func (x *GameMessage) GetAvatarLeave() *AvatarLeave {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_AvatarLeave); ok {
			return x.AvatarLeave
		}
	}
	return nil
}

func (x *GameMessage) GetAvatarMove() *AvatarMove {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_AvatarMove); ok {
			return x.AvatarMove
		}
	}
	return nil
}

func (x *GameMessage) GetRoomChange() *RoomChange {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_RoomChange); ok {
			return x.RoomChange
		}
	}
	return nil
}

func (x *GameMessage) GetChatMessage() *ChatReceive {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *GameMessage) GetPrivateMessageReceive() *PrivateMessageReceive {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_PrivateMessageReceive); ok {
			return x.PrivateMessageReceive
		}
	}
	return nil
}

func (x *GameMessage) GetSnap() *Snap {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Snap); ok {
			return x.Snap
		}
	}
	return nil
}

func (x *GameMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGameMessage_Payload interface {
	isGameMessage_Payload()
}

type GameMessage_Join struct {
	// Client → Server
	Join *JoinRequest `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type GameMessage_Position struct {
	Position *PositionUpdate `protobuf:"bytes,2,opt,name=position,proto3,oneof"`
}

type GameMessage_UseDoor struct {
	UseDoor *UseDoor `protobuf:"bytes,3,opt,name=use_door,json=useDoor,proto3,oneof"`
}

type GameMessage_Chat struct {
	Chat *ChatSend `protobuf:"bytes,4,opt,name=chat,proto3,oneof"`
}

type GameMessage_PrivateMessage struct {
	PrivateMessage *PrivateMessageSend `protobuf:"bytes,5,opt,name=private_message,json=privateMessage,proto3,oneof"`
}

type GameMessage_Leave struct {
	Leave *LeaveRequest `protobuf:"bytes,6,opt,name=leave,proto3,oneof"`
}

type GameMessage_Welcome struct {
	// Server → Client
	Welcome *Welcome `protobuf:"bytes,10,opt,name=welcome,proto3,oneof"`
}

type GameMessage_AvatarJoin struct {
	AvatarJoin *AvatarJoin `protobuf:"bytes,11,opt,name=avatar_join,json=avatarJoin,proto3,oneof"`
}

type GameMessage_AvatarLeave struct {
	AvatarLeave *AvatarLeave `protobuf:"bytes,12,opt,name=avatar_leave,json=avatarLeave,proto3,oneof"`
}

type GameMessage_AvatarMove struct {
	AvatarMove *AvatarMove `protobuf:"bytes,13,opt,name=avatar_move,json=avatarMove,proto3,oneof"`
}

type GameMessage_RoomChange struct {
	RoomChange *RoomChange `protobuf:"bytes,14,opt,name=room_change,json=roomChange,proto3,oneof"`
}

type GameMessage_ChatMessage struct {
	ChatMessage *ChatReceive `protobuf:"bytes,15,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type GameMessage_PrivateMessageReceive struct {
	PrivateMessageReceive *PrivateMessageReceive `protobuf:"bytes,16,opt,name=private_message_receive,json=privateMessageReceive,proto3,oneof"`
}

type GameMessage_Snap struct {
	Snap *Snap `protobuf:"bytes,17,opt,name=snap,proto3,oneof"`
}

type GameMessage_Error struct {
	Error *Error `protobuf:"bytes,18,opt,name=error,proto3,oneof"`
}

func (*GameMessage_Join) isGameMessage_Payload() {}

func (*GameMessage_Position) isGameMessage_Payload() {}

func (*GameMessage_UseDoor) isGameMessage_Payload() {}

func (*GameMessage_Chat) isGameMessage_Payload() {}

func (*GameMessage_PrivateMessage) isGameMessage_Payload() {}

func (*GameMessage_Leave) isGameMessage_Payload() {}

func (*GameMessage_Welcome) isGameMessage_Payload() {}

func (*GameMessage_AvatarJoin) isGameMessage_Payload() {}

func (*GameMessage_AvatarLeave) isGameMessage_Payload() {}

func (*GameMessage_AvatarMove) isGameMessage_Payload() {}

func (*GameMessage_RoomChange) isGameMessage_Payload() {}

func (*GameMessage_ChatMessage) isGameMessage_Payload() {}

func (*GameMessage_PrivateMessageReceive) isGameMessage_Payload() {}

func (*GameMessage_Snap) isGameMessage_Payload() {}

func (*GameMessage_Error) isGameMessage_Payload() {}

var File_offisims_protocol_v1_protocol_proto protoreflect.FileDescriptor

const file_offisims_protocol_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"#offisims/protocol/v1/protocol.proto\x12\x14offisims.protocol.v1\"\xf6\x01\n" +
	"\x0eAvatarSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\tR\vcharacterId\x12\x12\n" +
	"\x04room\x18\x04 \x01(\tR\x04room\x12\f\n" +
	"\x01x\x18\x05 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x06 \x01(\x02R\x01y\x12=\n" +
	"\tdirection\x18\a \x01(\x0e2\x1f.offisims.protocol.v1.DirectionR\tdirection\x12\x16\n" +
	"\x06moving\x18\b \x01(\bR\x06moving\x12\x16\n" +
	"\x06family\x18\t \x01(\tR\x06family\"P\n" +
	"\fRoomSnapshot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"#\n" +
	"\vJoinRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x83\x01\n" +
	"\x0ePositionUpdate\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12=\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x1f.offisims.protocol.v1.DirectionR\tdirection\x12\x16\n" +
	"\x06moving\x18\x04 \x01(\bR\x06moving\"\"\n" +
	"\aUseDoor\x12\x17\n" +
	"\adoor_id\x18\x01 \x01(\tR\x06doorId\"\x1e\n" +
	"\bChatSend\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"R\n" +
	"\x12PrivateMessageSend\x12(\n" +
	"\x10target_avatar_id\x18\x01 \x01(\tR\x0etargetAvatarId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x0e\n" +
	"\fLeaveRequest\"\xd0\x01\n" +
	"\aWelcome\x12\x1b\n" +
	"\tavatar_id\x18\x01 \x01(\tR\bavatarId\x126\n" +
	"\x04room\x18\x02 \x01(\v2\".offisims.protocol.v1.RoomSnapshotR\x04room\x12\x17\n" +
	"\aspawn_x\x18\x03 \x01(\x02R\x06spawnX\x12\x17\n" +
	"\aspawn_y\x18\x04 \x01(\x02R\x06spawnY\x12>\n" +
	"\aavatars\x18\x05 \x03(\v2$.offisims.protocol.v1.AvatarSnapshotR\aavatars\"J\n" +
	"\n" +
	"AvatarJoin\x12<\n" +
	"\x06avatar\x18\x01 \x01(\v2$.offisims.protocol.v1.AvatarSnapshotR\x06avatar\"*\n" +
	"\vAvatarLeave\x12\x1b\n" +
	"\tavatar_id\x18\x01 \x01(\tR\bavatarId\"\x9c\x01\n" +
	"\n" +
	"AvatarMove\x12\x1b\n" +
	"\tavatar_id\x18\x01 \x01(\tR\bavatarId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12=\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x1f.offisims.protocol.v1.DirectionR\tdirection\x12\x16\n" +
	"\x06moving\x18\x05 \x01(\bR\x06moving\"\xb6\x01\n" +
	"\n" +
	"RoomChange\x126\n" +
	"\x04room\x18\x01 \x01(\v2\".offisims.protocol.v1.RoomSnapshotR\x04room\x12\x17\n" +
	"\aspawn_x\x18\x02 \x01(\x02R\x06spawnX\x12\x17\n" +
	"\aspawn_y\x18\x03 \x01(\x02R\x06spawnY\x12>\n" +
	"\aavatars\x18\x04 \x03(\v2$.offisims.protocol.v1.AvatarSnapshotR\aavatars\"R\n" +
	"\vChatReceive\x12\x1b\n" +
	"\tavatar_id\x18\x01 \x01(\tR\bavatarId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x90\x01\n" +
	"\x15PrivateMessageReceive\x12$\n" +
	"\x0efrom_avatar_id\x18\x01 \x01(\tR\ffromAvatarId\x12\x1b\n" +
	"\tfrom_name\x18\x02 \x01(\tR\bfromName\x12 \n" +
	"\fto_avatar_id\x18\x03 \x01(\tR\n" +
	"toAvatarId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\"\n" +
	"\x04Snap\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x80\b\n" +
	"\vGameMessage\x127\n" +
	"\x04join\x18\x01 \x01(\v2!.offisims.protocol.v1.JoinRequestH\x00R\x04join\x12B\n" +
	"\bposition\x18\x02 \x01(\v2$.offisims.protocol.v1.PositionUpdateH\x00R\bposition\x12:\n" +
	"\buse_door\x18\x03 \x01(\v2\x1d.offisims.protocol.v1.UseDoorH\x00R\auseDoor\x124\n" +
	"\x04chat\x18\x04 \x01(\v2\x1e.offisims.protocol.v1.ChatSendH\x00R\x04chat\x12S\n" +
	"\x0fprivate_message\x18\x05 \x01(\v2(.offisims.protocol.v1.PrivateMessageSendH\x00R\x0eprivateMessage\x12:\n" +
	"\x05leave\x18\x06 \x01(\v2\".offisims.protocol.v1.LeaveRequestH\x00R\x05leave\x129\n" +
	"\awelcome\x18\n" +
	" \x01(\v2\x1d.offisims.protocol.v1.WelcomeH\x00R\awelcome\x12C\n" +
	"\vavatar_join\x18\v \x01(\v2 .offisims.protocol.v1.AvatarJoinH\x00R\n" +
	"avatarJoin\x12F\n" +
	"\favatar_leave\x18\f \x01(\v2!.offisims.protocol.v1.AvatarLeaveH\x00R\vavatarLeave\x12C\n" +
	"\vavatar_move\x18\r \x01(\v2 .offisims.protocol.v1.AvatarMoveH\x00R\n" +
	"avatarMove\x12C\n" +
	"\vroom_change\x18\x0e \x01(\v2 .offisims.protocol.v1.RoomChangeH\x00R\n" +
	"roomChange\x12F\n" +
	"\fchat_message\x18\x0f \x01(\v2!.offisims.protocol.v1.ChatReceiveH\x00R\vchatMessage\x12e\n" +
	"\x17private_message_receive\x18\x10 \x01(\v2+.offisims.protocol.v1.PrivateMessageReceiveH\x00R\x15privateMessageReceive\x120\n" +
	"\x04snap\x18\x11 \x01(\v2\x1a.offisims.protocol.v1.SnapH\x00R\x04snap\x123\n" +
	"\x05error\x18\x12 \x01(\v2\x1b.offisims.protocol.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload*u\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDIRECTION_DOWN\x10\x01\x12\x10\n" +
	"\fDIRECTION_UP\x10\x02\x12\x12\n" +
	"\x0eDIRECTION_LEFT\x10\x03\x12\x13\n" +
	"\x0fDIRECTION_RIGHT\x10\x04B\xd1\x01\n" +
	"\x18com.offisims.protocol.v1B\rProtocolProtoP\x01Z4github.com/offisims/game/internal/game/pb/protocolv1\xa2\x02\x03OPX\xaa\x02\x14Offisims.Protocol.V1\xca\x02\x14Offisims\\Protocol\\V1\xe2\x02 Offisims\\Protocol\\V1\\GPBMetadata\xea\x02\x16Offisims::Protocol::V1b\x06proto3"

var (
	file_offisims_protocol_v1_protocol_proto_rawDescOnce sync.Once
	file_offisims_protocol_v1_protocol_proto_rawDescData []byte
)

func file_offisims_protocol_v1_protocol_proto_rawDescGZIP() []byte {
	file_offisims_protocol_v1_protocol_proto_rawDescOnce.Do(func() {
		file_offisims_protocol_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_offisims_protocol_v1_protocol_proto_rawDesc), len(file_offisims_protocol_v1_protocol_proto_rawDesc)))
	})
	return file_offisims_protocol_v1_protocol_proto_rawDescData
}

var file_offisims_protocol_v1_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_offisims_protocol_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_offisims_protocol_v1_protocol_proto_goTypes = []any{
	(Direction)(0),                // 0: offisims.protocol.v1.Direction
	(*AvatarSnapshot)(nil),        // 1: offisims.protocol.v1.AvatarSnapshot
	(*RoomSnapshot)(nil),          // 2: offisims.protocol.v1.RoomSnapshot
	(*JoinRequest)(nil),           // 3: offisims.protocol.v1.JoinRequest
	(*PositionUpdate)(nil),        // 4: offisims.protocol.v1.PositionUpdate
	(*UseDoor)(nil),               // 5: offisims.protocol.v1.UseDoor
	(*ChatSend)(nil),              // 6: offisims.protocol.v1.ChatSend
	(*PrivateMessageSend)(nil),    // 7: offisims.protocol.v1.PrivateMessageSend
	(*LeaveRequest)(nil),          // 8: offisims.protocol.v1.LeaveRequest
	(*Welcome)(nil),               // 9: offisims.protocol.v1.Welcome
	(*AvatarJoin)(nil),            // 10: offisims.protocol.v1.AvatarJoin
	(*AvatarLeave)(nil),           // 11: offisims.protocol.v1.AvatarLeave
	(*AvatarMove)(nil),            // 12: offisims.protocol.v1.AvatarMove
	(*RoomChange)(nil),            // 13: offisims.protocol.v1.RoomChange
	(*ChatReceive)(nil),           // 14: offisims.protocol.v1.ChatReceive
	(*PrivateMessageReceive)(nil), // 15: offisims.protocol.v1.PrivateMessageReceive
	(*Snap)(nil),                  // 16: offisims.protocol.v1.Snap
	(*Error)(nil),                 // 17: offisims.protocol.v1.Error
	(*GameMessage)(nil),           // 18: offisims.protocol.v1.GameMessage
}
var file_offisims_protocol_v1_protocol_proto_depIdxs = []int32{
	0,  // 0: offisims.protocol.v1.AvatarSnapshot.direction:type_name -> offisims.protocol.v1.Direction
	0,  // 1: offisims.protocol.v1.PositionUpdate.direction:type_name -> offisims.protocol.v1.Direction
	2,  // 2: offisims.protocol.v1.Welcome.room:type_name -> offisims.protocol.v1.RoomSnapshot
	1,  // 3: offisims.protocol.v1.Welcome.avatars:type_name -> offisims.protocol.v1.AvatarSnapshot
	1,  // 4: offisims.protocol.v1.AvatarJoin.avatar:type_name -> offisims.protocol.v1.AvatarSnapshot
	0,  // 5: offisims.protocol.v1.AvatarMove.direction:type_name -> offisims.protocol.v1.Direction
	2,  // 6: offisims.protocol.v1.RoomChange.room:type_name -> offisims.protocol.v1.RoomSnapshot
	1,  // 7: offisims.protocol.v1.RoomChange.avatars:type_name -> offisims.protocol.v1.AvatarSnapshot
	3,  // 8: offisims.protocol.v1.GameMessage.join:type_name -> offisims.protocol.v1.JoinRequest
	4,  // 9: offisims.protocol.v1.GameMessage.position:type_name -> offisims.protocol.v1.PositionUpdate
	5,  // 10: offisims.protocol.v1.GameMessage.use_door:type_name -> offisims.protocol.v1.UseDoor
	6,  // 11: offisims.protocol.v1.GameMessage.chat:type_name -> offisims.protocol.v1.ChatSend
	7,  // 12: offisims.protocol.v1.GameMessage.private_message:type_name -> offisims.protocol.v1.PrivateMessageSend
	8,  // 13: offisims.protocol.v1.GameMessage.leave:type_name -> offisims.protocol.v1.LeaveRequest
	9,  // 14: offisims.protocol.v1.GameMessage.welcome:type_name -> offisims.protocol.v1.Welcome
	10, // 15: offisims.protocol.v1.GameMessage.avatar_join:type_name -> offisims.protocol.v1.AvatarJoin
	11, // 16: offisims.protocol.v1.GameMessage.avatar_leave:type_name -> offisims.protocol.v1.AvatarLeave
	12, // 17: offisims.protocol.v1.GameMessage.avatar_move:type_name -> offisims.protocol.v1.AvatarMove
	13, // 18: offisims.protocol.v1.GameMessage.room_change:type_name -> offisims.protocol.v1.RoomChange
	14, // 19: offisims.protocol.v1.GameMessage.chat_message:type_name -> offisims.protocol.v1.ChatReceive
	15, // 20: offisims.protocol.v1.GameMessage.private_message_receive:type_name -> offisims.protocol.v1.PrivateMessageReceive
	16, // 21: offisims.protocol.v1.GameMessage.snap:type_name -> offisims.protocol.v1.Snap
	17, // 22: offisims.protocol.v1.GameMessage.error:type_name -> offisims.protocol.v1.Error
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_offisims_protocol_v1_protocol_proto_init() }
func file_offisims_protocol_v1_protocol_proto_init() {
	if File_offisims_protocol_v1_protocol_proto != nil {
		return
	}
	file_offisims_protocol_v1_protocol_proto_msgTypes[17].OneofWrappers = []any{
		(*GameMessage_Join)(nil),
		(*GameMessage_Position)(nil),
		(*GameMessage_UseDoor)(nil),
		(*GameMessage_Chat)(nil),
		(*GameMessage_PrivateMessage)(nil),
		(*GameMessage_Leave)(nil),
		(*GameMessage_Welcome)(nil),
		(*GameMessage_AvatarJoin)(nil),
		(*GameMessage_AvatarLeave)(nil),
		(*GameMessage_AvatarMove)(nil),
		(*GameMessage_RoomChange)(nil),
		(*GameMessage_ChatMessage)(nil),
		(*GameMessage_PrivateMessageReceive)(nil),
		(*GameMessage_Snap)(nil),
		(*GameMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_offisims_protocol_v1_protocol_proto_rawDesc), len(file_offisims_protocol_v1_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_offisims_protocol_v1_protocol_proto_goTypes,
		DependencyIndexes: file_offisims_protocol_v1_protocol_proto_depIdxs,
		EnumInfos:         file_offisims_protocol_v1_protocol_proto_enumTypes,
		MessageInfos:      file_offisims_protocol_v1_protocol_proto_msgTypes,
	}.Build()
	File_offisims_protocol_v1_protocol_proto = out.File
	file_offisims_protocol_v1_protocol_proto_goTypes = nil
	file_offisims_protocol_v1_protocol_proto_depIdxs = nil
}
